version: "3"

services:
  web:
    container_name: debug-wasm-prod
    ports:
      - "1337:1337"
    environment:
      PORT: 1337
      ENVIRONMENT: "production"
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    healthcheck:
      test: curl -f http://localhost:1337/healthcheck || false
      interval: 30s
      timeout: 3s
