version: "3"

services:
  web:
    container_name: web-esolang
    ports:
      - "1337:1337"
    environment:
      PORT: 1337
      ENVIRONMENT: "development"
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    entrypoint: ["npm", "run", "dev"]
    volumes:
      - ./web/src:/app/src
      - ./web/views:/app/views
      - ./web/partials:/app/partials
      - ./tests:/app/tests
      - ./challenges:/app/challenges
