version: "3"

services:
  hackertools:
    container_name: hackertools
    ports:
      - "1337:1337"
    environment:
      PORT: 1337
      ENVIRONMENT: "production"
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ["npm", "start"]
