version: '3'
services:
  app:
    container_name: app
    restart: always
    build: .
    environment:
      - MONGO_INITDB_DATABASE=api2
      - MONGO_URL=mongodb://admin:46UeIA53nSKeeeryixbu@mongo:27017/api2?authSource=admin&readPreference=primary&directConnection=true&ssl=false
    ports:
      - '3000:3000'
    external_links:
      - mongo
  mongo:
    container_name: mongo_2
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=46UeIA53nSKeeeryixbu
      - MONGO_INITDB_DATABASE=api2
    ports:
      - '27017:27017'